# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_ui_square.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1910, 1000)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(280, 50, 300, 930))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMinimumSize(QtCore.QSize(300, 0))
        self.treeView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeView.setObjectName("treeView")
        self.parameterTreeWidget = ParameterTree(self.centralwidget)
        self.parameterTreeWidget.setGeometry(QtCore.QRect(10, 50, 260, 930))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.parameterTreeWidget.sizePolicy().hasHeightForWidth())
        self.parameterTreeWidget.setSizePolicy(sizePolicy)
        self.parameterTreeWidget.setMinimumSize(QtCore.QSize(260, 0))
        self.parameterTreeWidget.setAnimated(True)
        self.parameterTreeWidget.setHeaderHidden(True)
        self.parameterTreeWidget.setObjectName("parameterTreeWidget")
        self.parameterTreeWidget.headerItem().setText(0, "1")
        self.sessionName = QtWidgets.QLineEdit(self.centralwidget)
        self.sessionName.setEnabled(True)
        self.sessionName.setGeometry(QtCore.QRect(110, 11, 470, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sessionName.setFont(font)
        self.sessionName.setText("")
        self.sessionName.setAlignment(QtCore.Qt.AlignCenter)
        self.sessionName.setReadOnly(True)
        self.sessionName.setObjectName("sessionName")
        self.newSessionBtn = QtWidgets.QPushButton(self.centralwidget)
        self.newSessionBtn.setGeometry(QtCore.QRect(10, 10, 90, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.newSessionBtn.setFont(font)
        self.newSessionBtn.setObjectName("newSessionBtn")
        self.graphicsViewCMOS = GraphicsView(self.centralwidget)
        self.graphicsViewCMOS.setGeometry(QtCore.QRect(590, 120, 440, 440))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewCMOS.sizePolicy().hasHeightForWidth())
        self.graphicsViewCMOS.setSizePolicy(sizePolicy)
        self.graphicsViewCMOS.setMinimumSize(QtCore.QSize(440, 440))
        self.graphicsViewCMOS.setObjectName("graphicsViewCMOS")
        self.graphicsViewSampleSpecSeries = GraphicsView(self.centralwidget)
        self.graphicsViewSampleSpecSeries.setGeometry(QtCore.QRect(1040, 570, 860, 410))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.graphicsViewSampleSpecSeries.sizePolicy().hasHeightForWidth())
        self.graphicsViewSampleSpecSeries.setSizePolicy(sizePolicy)
        self.graphicsViewSampleSpecSeries.setMinimumSize(QtCore.QSize(0, 0))
        self.graphicsViewSampleSpecSeries.setObjectName("graphicsViewSampleSpecSeries")
        self.graphicsViewBinned = GraphicsView(self.centralwidget)
        self.graphicsViewBinned.setGeometry(QtCore.QRect(590, 10, 440, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graphicsViewBinned.sizePolicy().hasHeightForWidth())
        self.graphicsViewBinned.setSizePolicy(sizePolicy)
        self.graphicsViewBinned.setMinimumSize(QtCore.QSize(440, 100))
        self.graphicsViewBinned.setObjectName("graphicsViewBinned")
        self.graphicsViewSampleScanDepth = GraphicsView(self.centralwidget)
        self.graphicsViewSampleScanDepth.setGeometry(QtCore.QRect(1470, 220, 430, 340))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.graphicsViewSampleScanDepth.sizePolicy().hasHeightForWidth())
        self.graphicsViewSampleScanDepth.setSizePolicy(sizePolicy)
        self.graphicsViewSampleScanDepth.setMinimumSize(QtCore.QSize(420, 340))
        self.graphicsViewSampleScanDepth.setObjectName("graphicsViewSampleScanDepth")
        self.graphicsViewHeatmap = GraphicsView(self.centralwidget)
        self.graphicsViewHeatmap.setGeometry(QtCore.QRect(590, 570, 440, 410))
        self.graphicsViewHeatmap.setMinimumSize(QtCore.QSize(0, 0))
        self.graphicsViewHeatmap.setObjectName("graphicsViewHeatmap")
        self.graphicsViewSample = GraphicsView(self.centralwidget)
        self.graphicsViewSample.setGeometry(QtCore.QRect(1040, 10, 860, 200))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graphicsViewSample.sizePolicy().hasHeightForWidth())
        self.graphicsViewSample.setSizePolicy(sizePolicy)
        self.graphicsViewSample.setMinimumSize(QtCore.QSize(860, 200))
        self.graphicsViewSample.setObjectName("graphicsViewSample")
        self.graphicsViewSampleSpectrum = GraphicsView(self.centralwidget)
        self.graphicsViewSampleSpectrum.setGeometry(QtCore.QRect(1040, 220, 420, 340))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.graphicsViewSampleSpectrum.sizePolicy().hasHeightForWidth())
        self.graphicsViewSampleSpectrum.setSizePolicy(sizePolicy)
        self.graphicsViewSampleSpectrum.setMinimumSize(QtCore.QSize(420, 340))
        self.graphicsViewSampleSpectrum.setObjectName("graphicsViewSampleSpectrum")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Brillouin Scanning Interface"))
        self.newSessionBtn.setText(_translate("MainWindow", "New Session"))

from pyqtgraph.parametertree import ParameterTree
from pyqtgraph.widgets.GraphicsView import GraphicsView

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

